---
title: "予測モデリングプロジェクト"
author: "Shinya Hashimoto"
date: "2024-02-23"
output: html_document
---

## 概要

本プロジェクトでは、ウェアラブルデバイスから収集された加速度計のデータを使用して、運動実行の質を予測します。分析の目的は、演習の実行方法（`classe`変数）を予測することです。

## データの読み込みと前処理

```{r, cache=TRUE}
library(caret)
library(ggplot2)
library(rpart.plot)
library(corrplot)
set.seed(12345)

# データのダウンロード
trainingUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testingUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training <- read.csv(url(trainingUrl), na.strings=c("NA","#DIV/0!", ""))
testing <- read.csv(url(testingUrl), na.strings=c("NA","#DIV/0!", ""))
```

## データクリーニングと前処理

```{r, cache=TRUE}
# NA値を含む列を削除
training <- training[, colSums(is.na(training)) == 0]
testing <- testing[, colSums(is.na(testing)) == 0]

# 最初の7列を削除
training <- training[, -c(1:7)]
testing <- testing[, -c(1:7)]
```

## モデルの構築と評価

```{r, cache=TRUE}
subSamples <- createDataPartition(y=training$classe, p=0.75, list=FALSE)
subTraining <- training[subSamples,]
subTesting <- training[-subSamples,]

# トレーニングのコントロール設定
control <- trainControl(method="cv", number=3, verboseIter=TRUE)

# 各モデルの構築と評価
models <- c("rpart", "rf", "gbm", "svmLinear")
names(models) <- c("Decision Tree", "Random Forest", "Gradient Boosted Trees", "SVM")

# モデルの訓練
model_rpart <- train(classe ~ ., data=subTraining, method="rpart", trControl=control, tuneLength=1)
# テストデータに対する予測
prediction_rpart <- predict(model_rpart, subTesting)
# 予測の精度評価
cm_rpart <- confusionMatrix(prediction_rpart, subTesting$classe)
print(cm_rpart)

# モデルの訓練
model_rf <- train(classe ~ ., data=subTraining, method="gbm", trControl=control, tuneLength=1)
# テストデータに対する予測
prediction_rf <- predict(model_rf, subTesting)
# 予測の精度評価
cm_rf <- confusionMatrix(prediction_rf, subTesting$classe)
print(cm_rf)
```

## テストセットでの予測

```{r, cache=TRUE}
# Random Forestモデルを使用してテストセットの予測を行う
# Random Forestモデルを使用してテストセットの予測を行う
# results リストからランダムフォレストモデルを取得
best_model <- results[["rf"]]$model # 'rf' はランダムフォレストの略です

# テストデータセットに対する予測を実行
pred_rf <- predict(model_rf, testing) # subTesting を使用

# 予測結果の表示
print(pred_rf)

# 結果の詳細な評価（オプション）
cm_rf <- confusionMatrix(pred_rf, subTesting$classe)
print(cm_rf$overall['Accuracy'])
```
